secretKey: secretKey
server:
  ip: 127.0.0.1
  port: 2000
emailServer:
  smtp: smtp.gmail.com
  username: gmail_username
  password: gmail_password
rootuser:
  email: mateusz.jenek@gmail.com
  username: admin
  password: root
